storage_homepage:
    path:     /hello/{name}
    defaults: { _controller: RajStorageBundle:Default:index }

storage_direct:
    path:     /direct/{url}
    defaults: { _controller: RajStorageBundle:Storage:direct }
    requirements:
            _format:  json

storage_stories:
    path:     /stories/{board_id}
    defaults: { _controller: RajStorageBundle:Storage:stories }
    requirements:
            _format:  json

storage_phases:
    path:     /phases/{board_id}
    defaults: { _controller: RajStorageBundle:Storage:phases }
    requirements:
            _format:  json
