parameters:
  agilezen.class: Raj\StorageBundle\Utils\AgileZen
  agilezen.apikey: 'fa401a9d8aab4c968781fddf2119daba'
  agilezen.apiurl: 'https://agilezen.com/api/v1/'

  storage_manager.class: Raj\StorageBundle\Utils\StorageManager

services:
  agilezen:
    class: "%agilezen.class%"
    arguments:    [%agilezen.apikey%, %agilezen.apiurl%]

  storage_manager:
    class: "%storage_manager.class%"
    calls:
       - [ setRestClient, [ @agilezen ] ]